In [1]:
import os
import json
import gzip
import pandas as pd
from urllib.request import urlopen

import random
import numpy as np
from tqdm import tqdm_notebook as tqdm
from collections import defaultdict

In [2]:
# load all metadata
data = []
with open('data/Sports_and_Outdoors_5.json', 'r') as f:
    for l in tqdm(f):
        data.append(json.loads(l))

/var/folders/l2/_mks1sd56yjdxq9514qt1fnh0000gn/T/ipykernel_18656/3955769958.py:4: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for l in tqdm(f):

0it [00:00, ?it/s]

In [3]:
# show data
print(data[0])

{'overall': 5.0, 'verified': True, 'reviewTime': '06 3, 2015', 'reviewerID': 'A180LQZBUWVOLF', 'asin': '0000032034', 'reviewerName': 'Michelle A', 'reviewText': 'What a spectacular tutu! Very slimming.', 'summary': 'Five Stars', 'unixReviewTime': 1433289600}

In [8]:
df = []
for i in range(0,len(data)):
    df.append(pd.Series(data[i]))
df = pd.DataFrame(df)

In [9]:
df

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,style,vote,image
0,5.0,True,"06 3, 2015",A180LQZBUWVOLF,0000032034,Michelle A,What a spectacular tutu! Very slimming.,Five Stars,1433289600,NaN,NaN,NaN
1,1.0,True,"04 1, 2015",ATMFGKU5SVEYY,0000032034,Crystal R,What the heck? Is this a tutu for nuns? I know...,Is this a tutu for nuns?!,1427846400,NaN,NaN,NaN
2,5.0,True,"01 13, 2015",A1QE70QBJ8U6ZG,0000032034,darla Landreth,Exactly what we were looking for!,Five Stars,1421107200,NaN,NaN,NaN
3,5.0,True,"12 23, 2014",A22CP6Z73MZTYU,0000032034,L. Huynh,I used this skirt for a Halloween costume and ...,I liked that the elastic waist didn't dig in (...,1419292800,NaN,NaN,NaN
4,4.0,True,"12 15, 2014",A22L28G8NRNLLN,0000032034,McKenna,This is thick enough that you can't see throug...,This is thick enough that you can't see throug...,1418601600,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2839935,5.0,True,"04 5, 2018",A3TN0U64HONOPB,B01HJGAJ9O,Lewis Perez,"Love the shorts.. amazing comfortable, perfect...",Five Stars,1522886400,"{'Size:': ' Small', 'Color:': ' Black/White'}",NaN,NaN
2839936,5.0,True,"03 1, 2018",AJDQLM8PT3YWT,B01HJGAJ9O,Andrew M. Silverman,Superb quality,Five Stars,1519862400,"{'Size:': ' Large', 'Color:': ' Black/Nero'}",NaN,NaN
2839937,5.0,True,"03 17, 2018",A3QK5ZLRE2KHLL,B01HJHHBHG,old hunter,Works every time,Quality catcher,1521244800,NaN,NaN,NaN
2839938,5.0,True,"10 28, 2017",A3VDML80KNR9QQ,B01HJHHBHG,PJT,I have a briley bolt release paddle installed ...,Works for A400 with Briley Bolt Release,1509148800,NaN,NaN,NaN
2839939,5.0,True,"06 11, 2017",A3ONWSRNZFNC3U,B01HJHHBHG,goosedowner,Works great,Five Stars,1497139200,NaN,NaN,NaN

In [10]:
df.to_csv("data/reviews_sports.csv")